### ISSUE TITLE
WebSocket is not defined when running using node.js

### ISSUE THREAD

**Issue by shroo-paulli** [JSteunou/webstomp-client#65]
ReferenceError: WebSocket is not defined
    at Object.client (/Users/pongli/my/git/sandbox/JavaScript/ActivemqTest/node_modules/webstomp-client/dist/webstomp.js:881:18)
    at Object.<anonymous> (/Users/pongli/my/git/sandbox/JavaScript/ActivemqTest/webstomp-client.js:12:23)

I think you may need to import ws.

**Comment by JSteunou** [comment]
And I think you should read the doc ;) https://github.com/JSteunou/webstomp-client#nodejs-support
